import { agent } from "../agent";

export const obterDadosVendas = () => {
  const response = agent.Dashboard.obterVendas();
  return response;

  // return new Promise((resolve) => {
  //   setTimeout(() => {
  //     resolve([
  //       {
  //         Cliente: "Empresa X",
  //         Produto: "Celular",
  //         ValorTotal: 6500,
  //         Regiao: "Sul",
  //         DataEntrega: "05/12/2023",
  //       },
  //       {
  //         Cliente: "Negócios Y",
  //         Produto: "Celular",
  //         ValorTotal: 1200,
  //         Regiao: "Sul",
  //         DataEntrega: "10/12/2023",
  //       },
  //       {
  //         Cliente: "Comércio Z",
  //         Produto: "Celular",
  //         ValorTotal: 3000,
  //         Regiao: "Nordeste",
  //         DataEntrega: "15/12/2023",
  //       },
  //       {
  //         Cliente: "Indústria A",
  //         Produto: "Televisão",
  //         ValorTotal: 7000,
  //         Regiao: "Sudeste",
  //         DataEntrega: "20/12/2023",
  //       },
  //       {
  //         Cliente: "Serviços B",
  //         Produto: "Celular",
  //         ValorTotal: 1100,
  //         Regiao: "Centro-Oeste",
  //         DataEntrega: "25/12/2023",
  //       },
  //       {
  //         Cliente: "Loja C",
  //         Produto: "Notebook",
  //         ValorTotal: 5500,
  //         Regiao: "Norte",
  //         DataEntrega: "30/12/2023",
  //       },
  //       {
  //         Cliente: "Distribuidora D",
  //         Produto: "Notebook",
  //         ValorTotal: 6300,
  //         Regiao: "Sul",
  //         DataEntrega: "04/01/2024",
  //       },
  //       {
  //         Cliente: "Empresa E",
  //         Produto: "Celular",
  //         ValorTotal: 2000,
  //         Regiao: "Nordeste",
  //         DataEntrega: "09/01/2024",
  //       },
  //       {
  //         Cliente: "Comércio F",
  //         Produto: "Notebook",
  //         ValorTotal: 4500,
  //         Regiao: "Sudeste",
  //         DataEntrega: "14/01/2024",
  //       },
  //       {
  //         Cliente: "Indústria G",
  //         Produto: "Notebook",
  //         ValorTotal: 6100,
  //         Regiao: "Centro-Oeste",
  //         DataEntrega: "19/01/2024",
  //       },
  //       {
  //         Cliente: "Serviços H",
  //         Produto: "Celular",
  //         ValorTotal: 1300,
  //         Regiao: "Norte",
  //         DataEntrega: "24/01/2024",
  //       },
  //       {
  //         Cliente: "Loja I",
  //         Produto: "Notebook",
  //         ValorTotal: 5000,
  //         Regiao: "Sul",
  //         DataEntrega: "29/01/2024",
  //       },
  //       {
  //         Cliente: "Distribuidora J",
  //         Produto: "Televisão",
  //         ValorTotal: 6200,
  //         Regiao: "Nordeste",
  //         DataEntrega: "03/02/2024",
  //       },
  //       {
  //         Cliente: "Empresa K",
  //         Produto: "Celular",
  //         ValorTotal: 1500,
  //         Regiao: "Sudeste",
  //         DataEntrega: "08/02/2024",
  //       },
  //       {
  //         Cliente: "Comércio L",
  //         Produto: "Notebook",
  //         ValorTotal: 3500,
  //         Regiao: "Centro-Oeste",
  //         DataEntrega: "13/02/2024",
  //       },
  //       {
  //         Cliente: "Empresa M",
  //         Produto: "Celular",
  //         ValorTotal: 1750,
  //         Regiao: "Sudeste",
  //         DataEntrega: "18/02/2024",
  //       },
  //       {
  //         Cliente: "Negócios N",
  //         Produto: "Celular",
  //         ValorTotal: 2200,
  //         Regiao: "Nordeste",
  //         DataEntrega: "23/02/2024",
  //       },
  //       {
  //         Cliente: "Comércio O",
  //         Produto: "Celular",
  //         ValorTotal: 2600,
  //         Regiao: "Sul",
  //         DataEntrega: "28/02/2024",
  //       },
  //       {
  //         Cliente: "Indústria P",
  //         Produto: "Celular",
  //         ValorTotal: 1900,
  //         Regiao: "Centro-Oeste",
  //         DataEntrega: "05/03/2024",
  //       },
  //       {
  //         Cliente: "Serviços Q",
  //         Produto: "Celular",
  //         ValorTotal: 2100,
  //         Regiao: "Norte",
  //         DataEntrega: "10/03/2024",
  //       },
  //       {
  //         Cliente: "Loja R",
  //         Produto: "Notebook",
  //         ValorTotal: 5400,
  //         Regiao: "Sudeste",
  //         DataEntrega: "15/03/2024",
  //       },
  //       {
  //         Cliente: "Distribuidora S",
  //         Produto: "Notebook",
  //         ValorTotal: 5700,
  //         Regiao: "Nordeste",
  //         DataEntrega: "20/03/2024",
  //       },
  //       {
  //         Cliente: "Empresa T",
  //         Produto: "Notebook",
  //         ValorTotal: 6000,
  //         Regiao: "Sul",
  //         DataEntrega: "25/03/2024",
  //       },
  //       {
  //         Cliente: "Comércio U",
  //         Produto: "Notebook",
  //         ValorTotal: 4900,
  //         Regiao: "Centro-Oeste",
  //         DataEntrega: "30/03/2024",
  //       },
  //       {
  //         Cliente: "Indústria V",
  //         Produto: "Notebook",
  //         ValorTotal: 5200,
  //         Regiao: "Norte",
  //         DataEntrega: "04/04/2024",
  //       },
  //       {
  //         Cliente: "Serviços W",
  //         Produto: "Televisão",
  //         ValorTotal: 6800,
  //         Regiao: "Sudeste",
  //         DataEntrega: "09/04/2024",
  //       },
  //       {
  //         Cliente: "Loja X",
  //         Produto: "Televisão",
  //         ValorTotal: 7100,
  //         Regiao: "Nordeste",
  //         DataEntrega: "14/04/2024",
  //       },
  //       {
  //         Cliente: "Distribuidora Y",
  //         Produto: "Televisão",
  //         ValorTotal: 7400,
  //         Regiao: "Sul",
  //         DataEntrega: "19/04/2024",
  //       },
  //       {
  //         Cliente: "Empresa Z",
  //         Produto: "Televisão",
  //         ValorTotal: 6700,
  //         Regiao: "Centro-Oeste",
  //         DataEntrega: "24/04/2024",
  //       },
  //       {
  //         Cliente: "Negócios AA",
  //         Produto: "Televisão",
  //         ValorTotal: 7000,
  //         Regiao: "Norte",
  //         DataEntrega: "29/04/2024",
  //       },
  //     ]);
  //   }, 2000); // 2 segundos de atraso
  // });
};
